pipeline {
    agent any

    stages {
        stage("Install") {
            steps {
                dir('app') {
                    sh 'npm ci'
                }
            }
        }

        stage("Test") {
            steps {
                dir('app') {
                    sh 'npm test'
                }
            }
        }
    }
}