pipeline {
    agent any

    stages {
        stage("Install") {
            steps {
                dir('app') {
                    sh 'npm ci'
                }
            }
        }

        stage("Qualité") {
            parallel {
                stage("Lint") {
                    steps {
                        dir('app') {
                            sh 'npm run lint'
                        }
                    }
                }

                stage("Test") {
                    steps {
                        dir('app') {
                            sh 'npm run test:coverage'
                        }
                    }
                }
            }
        }

        stage("Docker Build") {
            steps {
                dir('app') {
                    sh 'docker build -t ecv-devops-app .'
                }
            }
        }
    }
}